"""empty message

Revision ID: 1343b6c6d180
Revises: 
Create Date: 2017-03-24 04:37:17.014000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1343b6c6d180'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserFolderPath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('folder_path', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserFolderPath_folder_path'), 'UserFolderPath', ['folder_path'], unique=True)
    op.create_index(op.f('ix_UserFolderPath_username'), 'UserFolderPath', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserFolderPath_username'), table_name='UserFolderPath')
    op.drop_index(op.f('ix_UserFolderPath_folder_path'), table_name='UserFolderPath')
    op.drop_table('UserFolderPath')
    # ### end Alembic commands ###
